name: example-environment
channels:
  - conda-forge

dependencies:
  - matplotlib==3.1.3
  - seaborn==0.9
  - networkx=2.4
  - numpy==1.18.1
  - pandas==1.0.1
  - geopandas==0.6.1
  - Fiona==1.8.11
  - scipy==1.4.1
  - tqdm==4.46.0
  - watermark==2.0.2
  - python-wget==3.2
  - shapely
  - Cartopy==0.18.0
  - ipywidgets
  - mapclassify==2.2.0
  - descartes
  - geoplot==0.4.0
  - jupyterlab>=1.0
  - jupyter==1.0.0
  - jupyter-contrib-nbextensions==0.5
